name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-19"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
# MY_VAR = "my-variable"
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWRhZDA4NDUtZjUwNS00MTMxLWEzOTMtNTkwYTQwYjIxMGE3IiwidGVuYW50X2lkIjoiNDU0OWFmOTg5MGZkZTU3OTQ5ZDg3ZDVlZTI0OWQ3NTZiZThhOTIzYTU3N2ZmYzcyNjE5NmM3YjM4OThhZDcwMCIsImludGVybmFsX3NlY3JldCI6ImE5MWY5OGJjLTc3NDgtNGEzYi1iNzY3LWIxZjYwMzZjYzA4YyJ9.x7HMa5fa2SrpM2EzY2XkPORwp3xImRSDhEpXXrokjFY"
JWT_SECRET = "whatthehell"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1